version: '3'

services:
  bot:
    container_name: GF-System
    deploy:
      restart_policy:
        condition: any
    environment:
      SENTRY_DSN:
      TOKEN:
      OWNER_ID:
      LOG_LEVEL: INFO
      LOG_CHANNEL:
      STEAM_API_KEY:
      MAINGUILD:
      STEAM_REDIRECT_URL: http://localhost:8000/test.html
    image: ghcr.io/gaming-network/gn-system
    volumes:
      - data:/app/HRP-Sys
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

volumes:
    data:
