services:
  bot:
    container_name: GF-System
    deploy:
      restart_policy:
        condition: any
    environment:
      SENTRY_DSN:
      TOKEN:
      OWNER_ID:
      LOG_LEVEL: INFO
      STEAM_API_KEY:
      STEAM_REDIRECT_URL: https://steamconnect.bloodygang.com/
    image: ghcr.io/hrp-development/hrp-system:latest
    volumes:
      - data:/app/HRP-Sys
      - /root/HRP-GamingVM-private.pem:/app/key.pem
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

volumes:
    data:
