name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64/v8]

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Push Docker Image
      run: |
        REPO_OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
        REPO_NAME=$(echo "${{ github.event.repository.name }}" | tr '[:upper:]' '[:lower:]')
        IMAGE_NAME="ghcr.io/$REPO_OWNER/$REPO_NAME"
        PLATFORM_TAG=$(echo "${{ matrix.platform }}" | tr '/' '-')
        docker buildx build \
          --no-cache \
          --compress \
          --platform ${{ matrix.platform }} \
          --tag $IMAGE_NAME:latest-${PLATFORM_TAG} \
          --tag $IMAGE_NAME:$(date +%s)-${PLATFORM_TAG} \
          --push ./gf-system
      shell: bash

  create-multiarch-latest:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Create Multi-Architecture Latest Tag
      run: |
        REPO_OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
        REPO_NAME=$(echo "${{ github.event.repository.name }}" | tr '[:upper:]' '[:lower:]')
        IMAGE_NAME="ghcr.io/$REPO_OWNER/$REPO_NAME"
        docker buildx imagetools create \
          --tag $IMAGE_NAME:latest \
          $IMAGE_NAME:linux-amd64 \
          $IMAGE_NAME:linux-arm64-v8 \
      shell: bash