name: Bauen und Pushen

on:
  push:
    branches:
      - master

jobs:
  build-and-notify:
    runs-on: self-hosted
    services:
      docker:
        image: docker:dind

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Check Docker
        run: docker --version
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.TOKEN }}

      - name: Build and push
        id: build-push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: ${{ github.ref == 'refs/heads/master' }} 
          cache-from: type=registry,ref=ghcr.io/gaming-network/gn-system:latest
          cache-to: type=inline
          tags: |
            ghcr.io/gaming-network/gn-system:latest
            ghcr.io/gaming-network/gn-system:${{ github.sha }}
          build-args: |
            git_sha=${{ github.sha }}

      - name: Debug Outputs
        run: |
          echo "Digest: ${{ steps.build-push.outputs.digest }}"
          echo "Tags: ${{ steps.build-push.outputs.tags }}"

      - name: Send Discord notification on success
        if: success()
        run: |
          curl -H "Content-Type: application/json" \
               -H "User-Agent: GitHub-Actions-Notifier" \
               -X POST \
               -d '{
                    "embeds": [{
                      "title": "✅ Discord Bot erfolgreich gebaut und hochgeladen!",
                      "description": "Das Docker-Image für den Discord Bot wurde erfolgreich erstellt und gepusht.",
                      "color": 3066993,
                      "fields": [
                        {
                          "name": "Branch",
                          "value": "${{ github.ref }}"
                        },
                        {
                          "name": "Commit",
                          "value": "${{ github.sha }}"
                        },
                        {
                          "name": "Image Digest",
                          "value": "${{ steps.build-push.outputs.digest }}"
                        }
                      ],
                      "footer": {
                        "text": "GN | System"
                      },
                      "timestamp": "${{ github.event.head_commit.timestamp }}"
                    }],
                    "avatar_url": "https://cdn.discordapp.com/avatars/1289365690146492418/1fcf3895b5c8486c802a704ea3505f81.webp?size=4096"
                  }' \
               ${{ secrets.DISCORD_WEBHOOK_URL }}

      - name: Send Discord notification on failure
        if: failure()  
        run: |
          curl -H "Content-Type: application/json" \
               -H "User-Agent: GitHub-Actions-Notifier" \
               -X POST \
               -d '{
                    "embeds": [{
                      "title": "❌ Fehler beim Bauen des Discord Bots.",
                      "description": "Das Docker-Image für den Discord Bot konnte nicht erstellt oder gepusht werden.",
                      "color": 15158332,
                      "fields": [
                        {
                          "name": "Branch",
                          "value": "${{ github.ref }}"
                        },
                        {
                          "name": "Commit",
                          "value": "${{ github.sha }}"
                        }
                      ],
                      "footer": {
                        "text": "GN | System"
                      },
                      "timestamp": "${{ github.event.head_commit.timestamp }}"
                    }],
                    "avatar_url": "https://cdn.discordapp.com/avatars/1289365690146492418/1fcf3895b5c8486c802a704ea3505f81.webp?size=4096"
                  }' \
               ${{ secrets.DISCORD_WEBHOOK_URL }}
