name: Build and Notify Discord

on:
  push:
    branches:
      - master

jobs:
  build-and-notify:
    runs-on: self-hosted
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/GN-System:latest

      - name: Send Discord Notification on Success
        if: success()
        run: |
          curl -H "Content-Type: application/json" \
               -H "User-Agent: GitHub-Actions-Notifier" \
               -X POST \
               -d '{
                    "content": "success",
                    "embeds": [{
                      "title": "✅ Discord Bot erfolgreich gebaut und hochgeladen!",
                      "description": "Das Docker-Image für den Discord Bot wurde erfolgreich erstellt und gepusht.",
                      "color": 3066993,
                      "fields": [
                        {
                          "name": "Branch",
                          "value": "${{ github.ref }}"
                        },
                        {
                          "name": "Commit",
                          "value": "${{ github.sha }}"
                        },
                        {
                          "name": "Image Digest",
                          "value": "${{ steps.push.outputs.digest }}"
                        }
                      ],
                      "footer": {
                        "text": "GN | System"
                      },
                      "timestamp": "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
                    }],
                    "avatar_url": "https://cdn.discordapp.com/avatars/1289365690146492418/1fcf3895b5c8486c802a704ea3505f81.webp?size=4096"
                  }' \
               ${{ secrets.DISCORD_WEBHOOK_URL }}

      - name: Send Discord Notification on Failure
        if: failure()  
        run: |
          curl -H "Content-Type: application/json" \
               -H "User-Agent: GitHub-Actions-Notifier" \
               -X POST \
               -d '{
                    "content": "error",
                    "embeds": [{
                      "title": "❌ Fehler beim Bauen des Discord Bots.",
                      "description": "Das Docker-Image für den Discord Bot konnte nicht erstellt oder gepusht werden.",
                      "color": 15158332,
                      "fields": [
                        {
                          "name": "Branch",
                          "value": "${{ github.ref }}"
                        },
                        {
                          "name": "Commit",
                          "value": "${{ github.sha }}"
                        }
                      ],
                      "footer": {
                        "text": "GN | System"
                      },
                      "timestamp": "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
                    }],
                    "avatar_url": "https://cdn.discordapp.com/avatars/1289365690146492418/1fcf3895b5c8486c802a704ea3505f81.webp?size=4096"
                  }' \
               ${{ secrets.DISCORD_WEBHOOK_URL }}
